fasta_dir: 'results/fastas'
fasta_extension: 'fasta'
res_dir: 'results'
coverage: 0.80
covmode: 0
clumode: 1
pid : 0
oldDB: null # <filename> <new fasta id> \t <path to old fasta>  \t <path to old seqDB> \t <path to old cluDb>\n
verbose: 1